### ISSUE TITLE
Histogram axis tick labels cut off

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#246]
In `Histogram` plugin, when the X or Y axis tick labels display large values (e.g., 1000 or larger), I cannot see the values on the plot, much less the axis labels. This is worse for the X axis because height is less than width. I use Qt toolkit.

Example:
![screenshot](https://cloud.githubusercontent.com/assets/2090236/11698966/ad936076-9e8f-11e5-93bd-c0938078a3d8.png)

**Comment by pllim** [comment]
Actually, I think this problem is global in all the plugins that use `matplotlib`. Perhaps could be addressed by #33?

**Comment by ejeschke** [comment]
I think using `tight_layout()` fixes the problem, but may introduce a different problem--the one you are seeing reported in #131.  At any rate, `tight_layout()` seems to put *too much* padding around the plot so that it ends up being really small.

**Comment by pllim** [comment]
I actually cannot confirm/deny the `tight_layout()` claim because it is only applied to `slit_plot`, not `cuts_plot`, and I never understood how to get Slit to work. I fixed the Cuts plot in #248 though.

**Comment by ejeschke** [comment]
Even with #248 merged I still see the numbers and labels being cut off (for `Cuts`).  We need some matplotlib expertise here, methinks.  If it is possible, we might be able to centralize it in `ginga.util.plots` so that all the plugin plots look nice.

**Comment by pllim** [comment]
@ejeschke , #248 fixed the shrinking, not the labels being cut off. I apologize for the confusion.

@mdboom ?

**Comment by pllim** [comment]
@ejeschke , in the meantime, is it possible to embed the plot within a scroll-able area? I tried the following in the plugin but it does not work (i.e., no scroll bars showed up):

```python
w = Plot.PlotWidget(self.plot)
w.resize(400, 300)
sw2 = Widgets.ScrollArea()
sw2.set_widget(w)
vbox.add_widget(sw2, stretch=1)
```

With the scroll bars, at least user has access to the whole plot until we figure out a better way to visualize the entire plot.

**Comment by ejeschke** [comment]
I think the problem is the way in which the plot is rendered within the space. It's not that the actual canvas (widget) is too large.  That would be why using the scroll area does not work.

I think the solution is going to involve using some matplotlib padding options.  Maybe setting some default left and bottom padding?  If we set it in `ginga.util.plots.Plot` it should fix most of the plugin plots.

**Comment by ejeschke** [comment]
It might also be fixed by using the appropriate setting for `dpi` when creating the matplotlib figure.

**Comment by pllim** [comment]
@ejeschke , changing `dpi` does not really solve the problem. However, tight layout (which the "easy" way to add padding) seems to partially work (see #253).

**Comment by pllim** [comment]
Fixed in #253.
